[Function]
Mix_AllocateChannels
Mix_CloseAudio
Mix_FadeInMusic
Mix_FadeOutMusic
Mix_FreeChunk
Mix_FreeMusic
Mix_HaltChannel
Mix_HaltMusic
Mix_LoadMUS
Mix_LoadMUSType_RW
Mix_LoadWAV_RW
Mix_OpenAudio
Mix_Pause
Mix_Paused
Mix_PlayChannelTimed
Mix_PlayMusic
Mix_Playing
Mix_PlayingMusic
Mix_QuerySpec
Mix_QuickLoad_RAW
Mix_RegisterEffect
Mix_Resume
Mix_SetPanning
Mix_SetPostMix
Mix_UnregisterEffect
Mix_Volume
Mix_VolumeMusic
