[Function]
utf8proc_category
utf8proc_charwidth
utf8proc_codepoint_valid
utf8proc_decompose_char
utf8proc_encode_char
utf8proc_get_property
utf8proc_grapheme_break_stateful
utf8proc_iterate
utf8proc_map
utf8proc_map_custom
utf8proc_NFC
utf8proc_NFD
utf8proc_NFKC
utf8proc_NFKD
utf8proc_tolower
utf8proc_toupper
