[Function]
sqlite3_close
sqlite3_column_int
sqlite3_create_function_v2
sqlite3_errmsg
sqlite3_exec
sqlite3_finalize
sqlite3_open
sqlite3_prepare_v2
sqlite3_result_int
sqlite3_step
sqlite3_update_hook
sqlite3_value_int
