[Function]
mpg123_chomp_string
mpg123_close
mpg123_decoder
mpg123_delete
mpg123_enc_from_id3_2
mpg123_exit
mpg123_free_string
mpg123_getparam2
mpg123_getformat
mpg123_id3
mpg123_init
mpg123_init_string
mpg123_length
mpg123_new
mpg123_open
mpg123_param2
mpg123_read
mpg123_scan
mpg123_seek
mpg123_set_string
mpg123_store_utf8_2
mpg123_strerror
mpg123_strlen
mpg123_tell
