[Function]
XRenderAddGlyphs
XRenderAddTraps
XRenderChangePicture
XRenderComposite
XRenderCompositeDoublePoly
XRenderCompositeString16
XRenderCompositeString32
XRenderCompositeString8
XRenderCompositeText16
XRenderCompositeText32
XRenderCompositeText8
XRenderCompositeTrapezoids
XRenderCompositeTriFan
XRenderCompositeTriStrip
XRenderCompositeTriangles
XRenderCreateAnimCursor
XRenderCreateConicalGradient
XRenderCreateCursor
XRenderCreateGlyphSet
XRenderCreateLinearGradient
XRenderCreatePicture
XRenderCreateRadialGradient
XRenderCreateSolidFill
XRenderFillRectangle
XRenderFillRectangles
XRenderFindDisplay
XRenderFindFormat
XRenderFindStandardFormat
XRenderFindVisualFormat
XRenderFreeGlyphSet
XRenderFreeGlyphs
XRenderFreePicture
XRenderParseColor
XRenderQueryExtension
XRenderQueryFilters
XRenderQueryFormats
XRenderQueryPictIndexValues
XRenderQuerySubpixelOrder
XRenderQueryVersion
XRenderReferenceGlyphSet
XRenderSetPictureClipRectangles
XRenderSetPictureClipRegion
XRenderSetPictureFilter
XRenderSetPictureTransform
XRenderSetSubpixelOrder
