vcpkg_download_distfile(ARCHIVE URLS "https://github.com/rockdaboot/libpsl/releases/download/${VERSION}/libpsl-${VERSION}.tar.gz" FILENAME "libpsl-${VERSION}.tar.gz" SHA512 c14d575cecc0f1693894dd79565b6b9220084ddfa43b908a1cefe16d147cdd5ec47796eb0c2135e2f829a951abaf39d8a371ab5c1352f57b36e610e25adf91f5)
vcpkg_extract_source_archive(SOURCE_PATH ARCHIVE "${ARCHIVE}" PATCHES patches/relocatable-fuzz-tests.patch)
vcpkg_configure_make(SOURCE_PATH "${SOURCE_PATH}" OPTIONS --disable-static --enable-shared --disable-runtime --enable-builtin)
vcpkg_install_make()
vcpkg_build_make(BUILD_TARGET check OPTIONS "TESTS=" LOGFILE_ROOT build-upstream-tests)
set(test_build "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/tests")
set(test_dest "${CURRENT_PACKAGES_DIR}/tools/libpsl/upstream-tests")
foreach(test_name IN ITEMS test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain)
    file(INSTALL "${test_build}/${test_name}" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
endforeach()
foreach(test_name IN ITEMS libpsl_fuzzer libpsl_load_fuzzer libpsl_load_dafsa_fuzzer)
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/fuzz/.libs/${test_name}" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
endforeach()
file(INSTALL "${test_build}/psl.dafsa" "${test_build}/psl_ascii.dafsa" DESTINATION "${test_dest}/data")
file(COPY "${SOURCE_PATH}/tests/" DESTINATION "${test_dest}/data/source")
file(COPY "${SOURCE_PATH}/fuzz/" DESTINATION "${test_dest}/data/fuzz")
cmake_path(GET SOURCE_PATH FILENAME source_leaf)
file(COPY "${SOURCE_PATH}/list/" DESTINATION "${test_dest}/data/src/${source_leaf}/list")
file(MAKE_DIRECTORY "${test_dest}/data/run/a")
file(INSTALL "${test_build}/psl.dafsa" "${test_build}/psl_ascii.dafsa" DESTINATION "${test_dest}/data/run/a")
vcpkg_fixup_pkgconfig()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
