[Function]
XScreenSaverAllocInfo
XScreenSaverGetRegistered
XScreenSaverQueryExtension
XScreenSaverQueryInfo
XScreenSaverQueryVersion
XScreenSaverRegister
XScreenSaverSelectInput
XScreenSaverSetAttributes
XScreenSaverSuspend
XScreenSaverUnregister
XScreenSaverUnsetAttributes
