[Function]
src_callback_new
src_callback_read
src_clone
src_delete
src_error
src_float_to_int_array
src_float_to_short_array
src_get_description
src_get_channels
src_get_name
src_get_version
src_int_to_float_array
src_is_valid_ratio
src_new
src_process
src_reset
src_set_ratio
src_short_to_float_array
src_simple
src_strerror
