vcpkg_download_distfile(ARCHIVE URLS "https://jugit.fz-juelich.de/mlz/libcerf/-/archive/v3.5/libcerf-v3.5.tar.gz" FILENAME "libcerf-v3.5.tar.gz" SHA512 cec86de9fa95375dad3313d0b25fa78357b34a0a76e4d833e699adaa2e4189dd6c4ccadc5ef97d91ca7d6f4cc7b94eb3d37779682e028a99860742c0e40e0db9)
vcpkg_extract_source_archive(SOURCE_PATH ARCHIVE "${ARCHIVE}" PATCHES clang-complex.patch)
vcpkg_cmake_configure(SOURCE_PATH "${SOURCE_PATH}" OPTIONS -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DCERF_C=ON -DCERF_CPP=OFF -DLIB_RUN=OFF -DLIB_MAN=OFF)
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/cerf PACKAGE_NAME cerf)
vcpkg_fixup_pkgconfig()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include" "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/libcerf/upstream-tests/build" USE_SOURCE_PERMISSIONS)
file(INSTALL "${SOURCE_PATH}/" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/libcerf/upstream-tests/source" USE_SOURCE_PERMISSIONS)
