[Function]
ov_test_callbacks
ov_clear
ov_halfrate_p
ov_info
ov_open_callbacks
ov_pcm_seek
ov_pcm_seek_page
ov_pcm_tell
ov_pcm_total
ov_raw_seek
ov_raw_tell
ov_read
ov_seekable
ov_time_seek
ov_time_seek_page
ov_time_tell
ov_time_total
