#pragma once

/*
 * Auto-generated by LoreTLC dump.
 * Config: Symbols.conf
 */

/*
 * Configured functions found only in non-header files:
 * - av_d3d11va_alloc_context [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/d3d11va.c
 * - av_qsv_alloc_context [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/qsv_api.c
 */

/*
 * Functions declared in this header:
 * - avpriv_ac3_parse_header [Function] (also seen in non-header files)
 */
#include "libavcodec/ac3_parser_internal.h"

/*
 * Functions declared in this header:
 * - avpriv_adts_header_parse [Function] (also seen in non-header files)
 */
#include "libavcodec/adts_header.h"

/*
 * Functions declared in this header:
 * - avpriv_codec_get_cap_skip_frame_fill_param [Function] (also seen in non-header files)
 * - avpriv_h264_has_num_reorder_frames [Function] (also seen in non-header files)
 */
#include "libavcodec/internal.h"

/*
 * Functions declared in this header:
 * - av_jni_get_java_vm [Function] (also seen in non-header files)
 * - av_jni_set_java_vm [Function] (also seen in non-header files)
 */
#include "libavcodec/jni.h"

/*
 * Functions declared in this header:
 * - av_mediacodec_alloc_context [Function] (also seen in non-header files)
 * - av_mediacodec_default_free [Function] (also seen in non-header files)
 * - av_mediacodec_default_init [Function] (also seen in non-header files)
 * - av_mediacodec_release_buffer [Function] (also seen in non-header files)
 * - av_mediacodec_render_buffer_at_time [Function] (also seen in non-header files)
 */
#include "libavcodec/mediacodec.h"

/*
 * Functions declared in this header:
 * - avpriv_mpeg4audio_get_config2 [Function] (also seen in non-header files)
 */
#include "libavcodec/mpeg4audio.h"

/*
 * Functions declared in this header:
 * - avpriv_mpegaudio_decode_header [Function] (also seen in non-header files)
 */
#include "libavcodec/mpegaudiodecheader.h"

/*
 * Functions declared in this header:
 * - avpriv_packet_list_free [Function] (also seen in non-header files)
 * - avpriv_packet_list_get [Function] (also seen in non-header files)
 * - avpriv_packet_list_put [Function] (also seen in non-header files)
 */
#include "libavcodec/packet_internal.h"

/*
 * Functions declared in this header:
 * - avpriv_get_raw_pix_fmt_tags [Function] (also seen in non-header files)
 * - avpriv_pix_fmt_find [Function] (also seen in non-header files)
 */
#include "libavcodec/raw.h"

/*
 * Functions declared in this header:
 * - avpriv_find_start_code [Function] (also seen in non-header files)
 */
#include "libavcodec/startcode.h"

/*
 * Functions declared in this header:
 * - avpriv_split_xiph_headers [Function] (also seen in non-header files)
 */
#include "libavcodec/xiph.h"

/*
 * Fallback declarations synthesized from non-header source files.
 * These are emitted after all includes so they may reuse already included types.
 */

/*
 * Fallback for av_d3d11va_alloc_context
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/d3d11va.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/d3d11va.c:42:26
 * Rewrites:
 * - return type rewritten: `struct AVD3D11VAContext *` -> `void *` because references types only seen in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/d3d11va.c
 * Status: declaration synthesized below
 */
void * av_d3d11va_alloc_context(void);

/*
 * Fallback for av_qsv_alloc_context
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/qsv_api.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/qsv_api.c:36:22
 * Rewrites:
 * - return type rewritten: `struct AVQSVContext *` -> `void *` because references types only seen in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/ffmpeg/vcpkg/hecate/buildtrees/ffmpeg/src/175e67f587-c5383740b0.clean/libavcodec/qsv_api.c
 * Status: declaration synthesized below
 */
void * av_qsv_alloc_context(void);

