#pragma once

/*
 * Auto-generated by LoreTLC dump.
 * Config: Symbols.conf
 */

/*
 * Configured functions found only in non-header files:
 * - FSEv05_buildDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_buildDTable_raw [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_buildDTable_rle [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_createDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_decompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_decompress_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_freeDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_getErrorName [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_isError [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv05_readNCount [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - FSEv06_buildDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_buildDTable_raw [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_buildDTable_rle [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_createDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_decompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_decompress_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_freeDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_getErrorName [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_isError [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv06_readNCount [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - FSEv07_buildDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_buildDTable_raw [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_buildDTable_rle [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_createDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_decompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_decompress_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_freeDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_getErrorName [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_isError [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - FSEv07_readNCount [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv05_decompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress1X2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress1X2_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress1X4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress1X4_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress4X2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress4X2_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress4X4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_decompress4X4_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_getErrorName [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_isError [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_readDTableX2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv05_readDTableX4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - HUFv06_decompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress1X2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress1X2_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress1X4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress1X4_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress4X2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress4X2_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress4X4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_decompress4X4_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_readDTableX2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv06_readDTableX4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - HUFv07_decompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X2_DCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X2_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X4_DCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X4_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X_DCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress1X_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X2_DCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X2_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X4_DCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X4_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X_DCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X_hufOnly [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_decompress4X_usingDTable [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_getErrorName [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_isError [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_readDTableX2 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_readDTableX4 [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_readStats [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - HUFv07_selectDecoder [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZBUFFv07_createDCtx_advanced [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTD_decodeLiteralsBlock_wrapper [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/decompress/zstd_decompress_block.c
 * - ZSTDv05_decompressBegin [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - ZSTDv05_decompressBlock [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - ZSTDv05_decompress_usingPreparedDCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - ZSTDv05_sizeofDCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * - ZSTDv06_decompressBegin [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - ZSTDv06_decompressBlock [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - ZSTDv06_decompress_usingPreparedDCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - ZSTDv06_sizeofDCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * - ZSTDv07_copyDCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_createDCtx_advanced [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_decompressBegin [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_decompressBegin_usingDict [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_decompressBlock [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_decompressContinue [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_estimateDCtxSize [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_insertBlock [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_isSkipFrame [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_nextSrcSizeToDecompress [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * - ZSTDv07_sizeofDCtx [Function] found only in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 */

/*
 * Fallback declarations synthesized from non-header source files.
 * These are emitted after all includes so they may reuse already included types.
 */

/*
 * Fallback for FSEv05_buildDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:600:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv05_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv05_buildDTable(void *dt, const short *normalizedCounter, unsigned int maxSymbolValue, unsigned int tableLog);

/*
 * Fallback for FSEv05_buildDTable_raw
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:900:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv05_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv05_buildDTable_raw(void *dt, unsigned int nbBits);

/*
 * Fallback for FSEv05_buildDTable_rle
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:903:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv05_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv05_buildDTable_rle(void *dt, unsigned char symbolValue);

/*
 * Fallback for FSEv05_createDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:592:16
 * Rewrites:
 * - return type rewritten: `FSEv05_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
void * FSEv05_createDTable(unsigned int tableLog);

/*
 * Fallback for FSEv05_decompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:550:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t FSEv05_decompress(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for FSEv05_decompress_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:608:8
 * Rewrites:
 * - parameter `dt` rewritten: `const FSEv05_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv05_decompress_usingDTable(void *dst, size_t dstCapacity, const void *cSrc, size_t cSrcSize, void *dt);

/*
 * Fallback for FSEv05_freeDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:593:13
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv05_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
void FSEv05_freeDTable(void *dt);

/*
 * Fallback for FSEv05_getErrorName
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:570:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
const char * FSEv05_getErrorName(size_t code);

/*
 * Fallback for FSEv05_isError
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:569:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
unsigned int FSEv05_isError(size_t code);

/*
 * Fallback for FSEv05_readNCount
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:586:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t FSEv05_readNCount(short *normalizedCounter, unsigned int *maxSymbolValuePtr, unsigned int *tableLogPtr, const void *rBuffer, size_t rBuffSize);

/*
 * Fallback for FSEv06_buildDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:665:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv06_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv06_buildDTable(void *dt, const short *normalizedCounter, unsigned int maxSymbolValue, unsigned int tableLog);

/*
 * Fallback for FSEv06_buildDTable_raw
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1004:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv06_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv06_buildDTable_raw(void *dt, unsigned int nbBits);

/*
 * Fallback for FSEv06_buildDTable_rle
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1007:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv06_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv06_buildDTable_rle(void *dt, unsigned char symbolValue);

/*
 * Fallback for FSEv06_createDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:659:16
 * Rewrites:
 * - return type rewritten: `FSEv06_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
void * FSEv06_createDTable(unsigned int tableLog);

/*
 * Fallback for FSEv06_decompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:616:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t FSEv06_decompress(void *dst, size_t dstCapacity, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for FSEv06_decompress_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:672:8
 * Rewrites:
 * - parameter `dt` rewritten: `const FSEv06_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv06_decompress_usingDTable(void *dst, size_t dstCapacity, const void *cSrc, size_t cSrcSize, void *dt);

/*
 * Fallback for FSEv06_freeDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:660:13
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv06_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
void FSEv06_freeDTable(void *dt);

/*
 * Fallback for FSEv06_getErrorName
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:627:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
const char * FSEv06_getErrorName(size_t code);

/*
 * Fallback for FSEv06_isError
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:626:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
unsigned int FSEv06_isError(size_t code);

/*
 * Fallback for FSEv06_readNCount
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:654:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t FSEv06_readNCount(short *normalizedCounter, unsigned int *maxSymbolValuePtr, unsigned int *tableLogPtr, const void *rBuffer, size_t rBuffSize);

/*
 * Fallback for FSEv07_buildDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:711:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv07_buildDTable(void *dt, const short *normalizedCounter, unsigned int maxSymbolValue, unsigned int tableLog);

/*
 * Fallback for FSEv07_buildDTable_raw
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:772:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv07_buildDTable_raw(void *dt, unsigned int nbBits);

/*
 * Fallback for FSEv07_buildDTable_rle
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:775:8
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv07_buildDTable_rle(void *dt, unsigned char symbolValue);

/*
 * Fallback for FSEv07_createDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:705:16
 * Rewrites:
 * - return type rewritten: `FSEv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
void * FSEv07_createDTable(unsigned int tableLog);

/*
 * Fallback for FSEv07_decompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:669:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t FSEv07_decompress(void *dst, size_t dstCapacity, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for FSEv07_decompress_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:718:8
 * Rewrites:
 * - parameter `dt` rewritten: `const FSEv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t FSEv07_decompress_usingDTable(void *dst, size_t dstCapacity, const void *cSrc, size_t cSrcSize, void *dt);

/*
 * Fallback for FSEv07_freeDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:706:13
 * Rewrites:
 * - parameter `dt` rewritten: `FSEv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
void FSEv07_freeDTable(void *dt);

/*
 * Fallback for FSEv07_getErrorName
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:675:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
const char * FSEv07_getErrorName(size_t code);

/*
 * Fallback for FSEv07_isError
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:674:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
unsigned int FSEv07_isError(size_t code);

/*
 * Fallback for FSEv07_readNCount
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:700:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t FSEv07_readNCount(short *normalizedCounter, unsigned int *maxSymbolValuePtr, unsigned int *tableLogPtr, const void *rBuffer, size_t rBuffSize);

/*
 * Fallback for HUFv05_decompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1528:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv05_decompress1X2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1636:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress1X2(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv05_decompress1X2_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1639:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress1X2_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned short *DTable);

/*
 * Fallback for HUFv05_decompress1X4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1637:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress1X4(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv05_decompress1X4_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1640:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress1X4_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned int *DTable);

/*
 * Fallback for HUFv05_decompress4X2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1614:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress4X2(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv05_decompress4X2_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1630:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress4X2_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned short *DTable);

/*
 * Fallback for HUFv05_decompress4X4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1615:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress4X4(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv05_decompress4X4_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1631:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_decompress4X4_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned int *DTable);

/*
 * Fallback for HUFv05_getErrorName
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1548:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
const char * HUFv05_getErrorName(size_t code);

/*
 * Fallback for HUFv05_isError
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1547:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
unsigned int HUFv05_isError(size_t code);

/*
 * Fallback for HUFv05_readDTableX2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1627:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_readDTableX2(unsigned short *DTable, const void *src, size_t srcSize);

/*
 * Fallback for HUFv05_readDTableX4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:1628:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv05_readDTableX4(unsigned int *DTable, const void *src, size_t srcSize);

/*
 * Fallback for HUFv06_decompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1665:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv06_decompress1X2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1772:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress1X2(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv06_decompress1X2_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1775:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress1X2_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned short *DTable);

/*
 * Fallback for HUFv06_decompress1X4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1773:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress1X4(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv06_decompress1X4_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1776:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress1X4_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned int *DTable);

/*
 * Fallback for HUFv06_decompress4X2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1753:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress4X2(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv06_decompress4X2_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1767:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress4X2_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned short *DTable);

/*
 * Fallback for HUFv06_decompress4X4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1754:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress4X4(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv06_decompress4X4_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1768:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_decompress4X4_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, const unsigned int *DTable);

/*
 * Fallback for HUFv06_readDTableX2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1764:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_readDTableX2(unsigned short *DTable, const void *src, size_t srcSize);

/*
 * Fallback for HUFv06_readDTableX4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:1765:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv06_readDTableX4(unsigned int *DTable, const void *src, size_t srcSize);

/*
 * Fallback for HUFv07_decompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:975:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress1X2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1079:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X2(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress1X2_DCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1032:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X2_DCtx(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress1X2_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1083:8
 * Rewrites:
 * - parameter `DTable` rewritten: `const HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X2_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, void *DTable);

/*
 * Fallback for HUFv07_decompress1X4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1080:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X4(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress1X4_DCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1033:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X4_DCtx(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress1X4_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1084:8
 * Rewrites:
 * - parameter `DTable` rewritten: `const HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X4_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, void *DTable);

/*
 * Fallback for HUFv07_decompress1X_DCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1031:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X_DCtx(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress1X_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1082:8
 * Rewrites:
 * - parameter `DTable` rewritten: `const HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress1X_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, void *DTable);

/*
 * Fallback for HUFv07_decompress4X2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1023:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X2(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress4X2_DCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1028:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X2_DCtx(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress4X2_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1074:8
 * Rewrites:
 * - parameter `DTable` rewritten: `const HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X2_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, void *DTable);

/*
 * Fallback for HUFv07_decompress4X4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1024:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X4(void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress4X4_DCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1029:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X4_DCtx(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress4X4_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1075:8
 * Rewrites:
 * - parameter `DTable` rewritten: `const HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X4_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, void *DTable);

/*
 * Fallback for HUFv07_decompress4X_DCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1026:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X_DCtx(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress4X_hufOnly
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1027:8
 * Rewrites:
 * - parameter `dctx` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X_hufOnly(void *dctx, void *dst, size_t dstSize, const void *cSrc, size_t cSrcSize);

/*
 * Fallback for HUFv07_decompress4X_usingDTable
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1073:8
 * Rewrites:
 * - parameter `DTable` rewritten: `const HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_decompress4X_usingDTable(void *dst, size_t maxDstSize, const void *cSrc, size_t cSrcSize, void *DTable);

/*
 * Fallback for HUFv07_getErrorName
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:986:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
const char * HUFv07_getErrorName(size_t code);

/*
 * Fallback for HUFv07_isError
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:985:13
 * Rewrites: none
 * Status: declaration synthesized below
 */
unsigned int HUFv07_isError(size_t code);

/*
 * Fallback for HUFv07_readDTableX2
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1070:8
 * Rewrites:
 * - parameter `DTable` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_readDTableX2(void *DTable, const void *src, size_t srcSize);

/*
 * Fallback for HUFv07_readDTableX4
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1071:8
 * Rewrites:
 * - parameter `DTable` rewritten: `HUFv07_DTable *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_readDTableX4(void *DTable, const void *src, size_t srcSize);

/*
 * Fallback for HUFv07_readStats
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1051:8
 * Rewrites:
 * - parameter `huffWeight` rewritten: `BYTE *` -> `void *` because pointee type could not be resolved to an included header
 * - parameter `rankStats` rewritten: `U32 *` -> `void *` because pointee type could not be resolved to an included header
 * - parameter `nbSymbolsPtr` rewritten: `U32 *` -> `void *` because pointee type could not be resolved to an included header
 * - parameter `tableLogPtr` rewritten: `U32 *` -> `void *` because pointee type could not be resolved to an included header
 * Status: declaration synthesized below
 */
size_t HUFv07_readStats(void *huffWeight, size_t hwSize, void *rankStats, void *nbSymbolsPtr, void *tableLogPtr, const void *src, size_t srcSize);

/*
 * Fallback for HUFv07_selectDecoder
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:1068:5
 * Rewrites: none
 * Status: declaration synthesized below
 */
U32 HUFv07_selectDecoder(size_t dstSize, size_t cSrcSize);

/*
 * Fallback for ZBUFFv07_createDCtx_advanced
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:4278:31
 * Rewrites:
 * - return type rewritten: `ZBUFFv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: cannot synthesize declaration
 * - parameter `customMem` of type `ZSTDv07_customMem` cannot be emitted: references types only seen in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 */

/*
 * Fallback for ZSTD_decodeLiteralsBlock_wrapper
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/decompress/zstd_decompress_block.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/decompress/zstd_decompress_block.c:343:8
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTD_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/zstd.h
 * Status: declaration synthesized below
 */
size_t ZSTD_decodeLiteralsBlock_wrapper(void *dctx, const void *src, size_t srcSize, void *dst, size_t dstCapacity);

/*
 * Fallback for ZSTDv05_decompressBegin
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:278:8
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv05_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.h
 * Status: declaration synthesized below
 */
size_t ZSTDv05_decompressBegin(void *dctx);

/*
 * Fallback for ZSTDv05_decompressBlock
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:332:8
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv05_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.h
 * Status: declaration synthesized below
 */
size_t ZSTDv05_decompressBlock(void *dctx, void *dst, size_t dstCapacity, const void *src, size_t srcSize);

/*
 * Fallback for ZSTDv05_decompress_usingPreparedDCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:269:8
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv05_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.h
 * - parameter `preparedDCtx` rewritten: `const ZSTDv05_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.h
 * Status: declaration synthesized below
 */
size_t ZSTDv05_decompress_usingPreparedDCtx(void *dctx, void *preparedDCtx, void *dst, size_t dstCapacity, const void *src, size_t srcSize);

/*
 * Fallback for ZSTDv05_sizeofDCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v05.c:2613:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t ZSTDv05_sizeofDCtx(void);

/*
 * Fallback for ZSTDv06_decompressBegin
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:286:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv06_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.h
 * Status: declaration synthesized below
 */
size_t ZSTDv06_decompressBegin(void *dctx);

/*
 * Fallback for ZSTDv06_decompressBlock
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:345:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv06_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.h
 * Status: declaration synthesized below
 */
size_t ZSTDv06_decompressBlock(void *dctx, void *dst, size_t dstCapacity, const void *src, size_t srcSize);

/*
 * Fallback for ZSTDv06_decompress_usingPreparedDCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:275:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv06_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.h
 * - parameter `preparedDCtx` rewritten: `const ZSTDv06_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.h
 * Status: declaration synthesized below
 */
size_t ZSTDv06_decompress_usingPreparedDCtx(void *dctx, void *preparedDCtx, void *dst, size_t dstCapacity, const void *src, size_t srcSize);

/*
 * Fallback for ZSTDv06_sizeofDCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v06.c:2770:8
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t ZSTDv06_sizeofDCtx(void);

/*
 * Fallback for ZSTDv07_copyDCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:92:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * - parameter `preparedDCtx` rewritten: `const ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
void ZSTDv07_copyDCtx(void *dctx, void *preparedDCtx);

/*
 * Fallback for ZSTDv07_createDCtx_advanced
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:79:30
 * Rewrites:
 * - return type rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: cannot synthesize declaration
 * - parameter `customMem` of type `ZSTDv07_customMem` cannot be emitted: references types only seen in non-header files: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 */

/*
 * Fallback for ZSTDv07_decompressBegin
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:90:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_decompressBegin(void *dctx);

/*
 * Fallback for ZSTDv07_decompressBegin_usingDict
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:91:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_decompressBegin_usingDict(void *dctx, const void *dict, size_t dictSize);

/*
 * Fallback for ZSTDv07_decompressBlock
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:176:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_decompressBlock(void *dctx, void *dst, size_t dstCapacity, const void *src, size_t srcSize);

/*
 * Fallback for ZSTDv07_decompressContinue
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:95:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_decompressContinue(void *dctx, void *dst, size_t dstCapacity, const void *src, size_t srcSize);

/*
 * Fallback for ZSTDv07_estimateDCtxSize
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:75:23
 * Rewrites: none
 * Status: declaration synthesized below
 */
size_t ZSTDv07_estimateDCtxSize(void);

/*
 * Fallback for ZSTDv07_insertBlock
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:177:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_insertBlock(void *dctx, const void *blockStart, size_t blockSize);

/*
 * Fallback for ZSTDv07_isSkipFrame
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:2901:5
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
int ZSTDv07_isSkipFrame(void *dctx);

/*
 * Fallback for ZSTDv07_nextSrcSizeToDecompress
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:94:23
 * Rewrites:
 * - parameter `dctx` rewritten: `ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_nextSrcSizeToDecompress(void *dctx);

/*
 * Fallback for ZSTDv07_sizeofDCtx
 * Source: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c
 * Source location: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.c:83:23
 * Rewrites:
 * - parameter `dctx` rewritten: `const ZSTDv07_DCtx *` -> `void *` because requires types from headers not already included: /home/user/eurosys-lorelei-artifacts/.work/evaluations/zstd/vcpkg/native/buildtrees/zstd/src/v1.5.7-c05a84fcce.clean/lib/legacy/zstd_v07.h
 * Status: declaration synthesized below
 */
size_t ZSTDv07_sizeofDCtx(void *dctx);

