vcpkg_download_distfile(ARCHIVE URLS "https://ftp.gnu.org/gnu/libidn/libidn-${VERSION}.tar.gz" FILENAME "libidn-${VERSION}.tar.gz" SHA512 a098d9c1df9d47181e7707a115dcfa12ba4b1aba68b1d070eff4f0578fd2e09b9c453457f83fc1a704726eac3a6f90e5a00772ab116affd07efe1e1ab9d5b0f1)
vcpkg_extract_source_archive(SOURCE_PATH ARCHIVE "${ARCHIVE}")
vcpkg_configure_make(SOURCE_PATH "${SOURCE_PATH}" OPTIONS --enable-shared --disable-static --disable-doc --disable-nls --disable-java --disable-csharp)
vcpkg_install_make()
vcpkg_build_make(BUILD_TARGET check OPTIONS "TESTS=" LOGFILE_ROOT build-upstream-tests)
set(test_build "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/tests")
set(test_dest "${CURRENT_PACKAGES_DIR}/tools/libidn/upstream-tests")
foreach(test_name IN ITEMS tst_stringprep tst_punycode tst_idna tst_idna2 tst_idna3 tst_idna4 tst_nfkc tst_pr29 tst_strerror tst_toutf8 tst_symbols tst_badutf8 tst_utf8crash tst_toascii64oob tst_badutf8nfkc tst_versions tst_tld)
    file(INSTALL "${test_build}/${test_name}" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
endforeach()
file(COPY "${SOURCE_PATH}/tests/" DESTINATION "${test_dest}/data")
vcpkg_fixup_pkgconfig()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING.LESSERv3")
