vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH REPO xiph/ogg REF v1.3.6 SHA512 c247e1da8b12f8b33272fafb6d7c171a1a2687c3632977439fa60b96ccc2ad751d88a2931bb3e18e1ddf2eea2e82cdd0aab087b2ec5393a9228c703476fa0167 HEAD_REF master PATCHES patches/shared-selftests.patch)
vcpkg_cmake_configure(SOURCE_PATH "${SOURCE_PATH}" OPTIONS -DBUILD_SHARED_LIBS=ON -DINSTALL_DOCS=OFF -DINSTALL_PKG_CONFIG_MODULE=ON -DBUILD_TESTING=ON)
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/Ogg PACKAGE_NAME ogg)
vcpkg_fixup_pkgconfig()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include" "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING")
file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/libogg/upstream-tests/build" USE_SOURCE_PERMISSIONS)
file(INSTALL "${SOURCE_PATH}/" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/libogg/upstream-tests/source" USE_SOURCE_PERMISSIONS)
