vcpkg_download_distfile(ARCHIVE URLS "https://ftp.gnu.org/gnu/libidn/libidn2-${VERSION}.tar.gz" FILENAME "libidn2-${VERSION}.tar.gz" SHA512 4d8427c0f115268132f7544e80a808c883ab1406338f6c529b1a586b016d57aedb0857f66166eb8d9f37d70efc9dccf907b673b43b17bcf258c8797db1e829ce)
vcpkg_extract_source_archive(SOURCE_PATH ARCHIVE "${ARCHIVE}" PATCHES patches/relocatable-tests.patch patches/avoid-getline-in-installed-test.patch)
set(CONFIGURE_TRIPLET)
if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
    set(CONFIGURE_TRIPLET BUILD_TRIPLET "--host=x86_64-linux-gnu")
endif()
vcpkg_configure_make(SOURCE_PATH "${SOURCE_PATH}" ${CONFIGURE_TRIPLET}
    OPTIONS --enable-shared --disable-static --disable-doc --disable-gtk-doc --disable-nls --disable-gcc-warnings --with-included-libunistring --enable-cross-guesses=risky)
vcpkg_install_make()
vcpkg_build_make(BUILD_TARGET check OPTIONS "TESTS=" LOGFILE_ROOT build-upstream-tests)
set(test_build "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel")
set(test_dest "${CURRENT_PACKAGES_DIR}/tools/libidn2/upstream-tests")
foreach(test_name IN ITEMS test-version test-strerror test-locale test-tounicode test-punycode test-compat-punycode test-IdnaTest-inc test-IdnaTest-txt test-lookup test-register test-glibc)
    if(EXISTS "${test_build}/tests/${test_name}")
        file(INSTALL "${test_build}/tests/${test_name}" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
    endif()
endforeach()
file(INSTALL "${test_build}/src/.libs/idn2" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
foreach(test_name IN ITEMS libidn2_to_ascii_8z_fuzzer libidn2_to_unicode_8z8z_fuzzer libidn2_register_fuzzer)
    file(INSTALL "${test_build}/fuzz/${test_name}" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
endforeach()
file(COPY "${SOURCE_PATH}/tests/" DESTINATION "${test_dest}/data/tests")
file(COPY "${SOURCE_PATH}/fuzz/" DESTINATION "${test_dest}/data/fuzz")
vcpkg_fixup_pkgconfig()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING.LESSERv3" "${SOURCE_PATH}/COPYINGv2" "${SOURCE_PATH}/COPYING.unicode")
