[Function]
WavpackCloseFile
WavpackFlushSamples
WavpackGetBytesPerSample
WavpackGetLibraryVersionString
WavpackGetMD5Sum
WavpackGetMode
WavpackGetNumChannels
WavpackGetNumErrors
WavpackGetNumSamples64
WavpackGetQualifyMode
WavpackOpenFileInput
WavpackOpenFileInputEx
WavpackOpenFileOutput
WavpackPackInit
WavpackPackSamples
WavpackSeekSample
WavpackSeekSample64
WavpackSetConfiguration64
WavpackStoreMD5Sum
WavpackUnpackSamples
lore_wavpack_block_output_signature
