if(NOT TARGET_TRIPLET MATCHES "-ae$")
    message(STATUS "Using the C library iconv for the non-AE host triplet")
    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
    file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/share/iconv")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake"
        DESTINATION "${CURRENT_PACKAGES_DIR}/share/iconv")
    return()
endif()

vcpkg_download_distfile(ARCHIVE URLS "https://ftp.gnu.org/gnu/libiconv/libiconv-${VERSION}.tar.gz" FILENAME "libiconv-${VERSION}.tar.gz" SHA512 a55eb3b7b785a78ab8918db8af541c9e11deb5ff4f89d54483287711ed797d87848ce0eafffa7ce26d9a7adb4b5a9891cb484f94bd4f51d3ce97a6a47b4c719a)
vcpkg_extract_source_archive(SOURCE_PATH ARCHIVE "${ARCHIVE}")
set(CONFIGURE_TRIPLET)
if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
    set(CONFIGURE_TRIPLET BUILD_TRIPLET "--host=x86_64-linux-gnu")
endif()
vcpkg_configure_make(SOURCE_PATH "${SOURCE_PATH}" ${CONFIGURE_TRIPLET}
    OPTIONS --enable-shared --disable-static --enable-extra-encodings --without-libiconv-prefix --without-libintl-prefix)
vcpkg_install_make()
file(COPY "${SOURCE_PATH}/tests/genutf8.c" "${SOURCE_PATH}/tests/gengb18030z.c" DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/tests")
file(COPY "${SOURCE_PATH}/srclib/binary-io.h" DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/srclib")
foreach(test_name IN ITEMS table-from table-to is-native test-shiftseq test-to-wchar test-bom-state test-discard)
    vcpkg_build_make(BUILD_TARGET "${test_name}" SUBPATH tests LOGFILE_ROOT "build-upstream-${test_name}")
endforeach()
foreach(test_name IN ITEMS genutf8 gengb18030z)
    vcpkg_build_make(BUILD_TARGET "${test_name}" SUBPATH tests OPTIONS "CPPFLAGS=-I.. -I../srclib" LOGFILE_ROOT "build-upstream-${test_name}")
endforeach()
set(test_build "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel")
set(test_dest "${CURRENT_PACKAGES_DIR}/tools/libiconv/upstream-tests")
file(INSTALL "${test_build}/src/.libs/iconv_no_i18n" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
foreach(test_name IN ITEMS table-from table-to test-shiftseq test-to-wchar test-bom-state test-discard)
    file(INSTALL "${test_build}/tests/.libs/${test_name}" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
endforeach()
file(INSTALL "${test_build}/tests/is-native" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
file(COPY "${SOURCE_PATH}/tests/" DESTINATION "${test_dest}/data")
file(COPY "${test_build}/tests/Makefile" DESTINATION "${test_dest}/tests")
file(READ "${test_dest}/tests/Makefile" test_makefile)
string(REGEX REPLACE "srcdir = [^\n]*" "srcdir = ../data" test_makefile "${test_makefile}")
foreach(test_name IN ITEMS table-from table-to is-native test-shiftseq test-to-wchar test-bom-state test-discard)
    string(REGEX REPLACE "${test_name} :[^\n]*" "${test_name} :" test_makefile "${test_makefile}")
endforeach()
file(WRITE "${test_dest}/tests/Makefile" "${test_makefile}")
vcpkg_replace_string("${test_dest}/tests/Makefile"
    "\t\$(CC) \$(LDFLAGS) \$(INCLUDES) \$(CFLAGS) \$(CPPFLAGS) \$(srcdir)/genutf8.c ../srclib/libicrt.a -o genutf8 && \\\n"
    "\tcp ../bin/genutf8 genutf8 && \\\n")
vcpkg_replace_string("${test_dest}/tests/Makefile"
    "\t\$(CC) \$(LDFLAGS) \$(INCLUDES) \$(CFLAGS) \$(CPPFLAGS) \$(srcdir)/gengb18030z.c ../srclib/libicrt.a -o gengb18030z && \\\n"
    "\tcp ../bin/gengb18030z gengb18030z && \\\n")
foreach(test_name IN ITEMS table-from table-to test-shiftseq test-to-wchar test-bom-state test-discard)
    file(INSTALL "${test_build}/tests/.libs/${test_name}" DESTINATION "${test_dest}/tests" TYPE PROGRAM)
endforeach()
file(INSTALL "${test_build}/tests/is-native" DESTINATION "${test_dest}/tests" TYPE PROGRAM)
file(INSTALL "${test_build}/tests/genutf8" "${test_build}/tests/gengb18030z" DESTINATION "${test_dest}/bin" TYPE PROGRAM)
file(INSTALL "${test_build}/src/.libs/iconv_no_i18n" DESTINATION "${test_dest}/src" TYPE PROGRAM)
file(COPY "${test_build}/srclib/libicrt.a" DESTINATION "${test_dest}/srclib")
file(GLOB srclib_headers "${SOURCE_PATH}/srclib/*.h")
file(COPY ${srclib_headers} DESTINATION "${test_dest}/srclib")
file(GLOB configured_srclib_headers "${test_build}/srclib/*.h")
file(COPY ${configured_srclib_headers} DESTINATION "${test_dest}/srclib")
file(COPY "${test_build}/include/" DESTINATION "${test_dest}/include")
file(COPY "${test_build}/config.h" DESTINATION "${test_dest}")
set(VCPKG_POLICY_ALLOW_RESTRICTED_HEADERS enabled)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share" "${CURRENT_PACKAGES_DIR}/share/doc")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING.LIB" "${SOURCE_PATH}/COPYING")
