foreach(mode IN ITEMS native hecate)
    add_test(NAME ${mode}.simple COMMAND "${TEST_LAUNCHER}" "${mode}" "${TEST_${mode}_ROOT}/simple")
    add_test(NAME ${mode}.lzotest-lzo COMMAND "${TEST_LAUNCHER}" "${mode}" "${TEST_${mode}_ROOT}/lzotest" -mlzo -n2 -q "${TEST_${mode}_DATA}/COPYING")
    add_test(NAME ${mode}.lzotest-avail COMMAND "${TEST_LAUNCHER}" "${mode}" "${TEST_${mode}_ROOT}/lzotest" -mavail -n10 -q "${TEST_${mode}_DATA}/COPYING")
    add_test(NAME ${mode}.lzotest-all COMMAND "${TEST_LAUNCHER}" "${mode}" "${TEST_${mode}_ROOT}/lzotest" -mall -n10 -q "${TEST_${mode}_DATA}/lzodefs.h")
    add_test(NAME ${mode}.align COMMAND "${TEST_LAUNCHER}" "${mode}" "${TEST_${mode}_ROOT}/align")
    add_test(NAME ${mode}.chksum COMMAND "${TEST_LAUNCHER}" "${mode}" "${TEST_${mode}_ROOT}/chksum")
endforeach()
add_test(NAME native.testmini COMMAND "${TEST_LAUNCHER}" native "${TEST_native_ROOT}/testmini")
