[Function]
glBufferRegionEnabled
glBufferPageCommitmentMemNV
glDeleteBufferRegion
glDrawBufferRegion
glNamedFramebufferTextureMultiviewOVR
glNamedBufferPageCommitmentMemNV
glNewBufferRegion
glReadBufferRegion
glTexPageCommitmentMemNV
glTexturePageCommitmentMemNV
