[Function]
vkCmdBeginRenderPass2KHR
vkCmdEndRenderPass2KHR
vkCmdNextSubpass2KHR
vkCreateDescriptorUpdateTemplateKHR
vkCreateRenderPass2KHR
vkCreateXlibSurfaceKHR
vkDestroyDescriptorUpdateTemplateKHR
vkGetBufferMemoryRequirements2KHR
vkGetImageMemoryRequirements2KHR
vkGetImageSparseMemoryRequirements2KHR
vkGetPhysicalDeviceFeatures2KHR
vkGetPhysicalDeviceFormatProperties2KHR
vkGetPhysicalDeviceImageFormatProperties2KHR
vkGetPhysicalDeviceMemoryProperties2KHR
vkGetPhysicalDeviceProperties2KHR
vkGetPhysicalDeviceQueueFamilyProperties2KHR
vkGetPhysicalDeviceSparseImageFormatProperties2KHR
vkGetPhysicalDeviceXlibPresentationSupportKHR
vkUpdateDescriptorSetWithTemplateKHR
