[Function]
SDL_AudioDriverName
SDL_CloseAudio
SDL_CreateRGBSurfaceFrom
SDL_EnableKeyRepeat
SDL_EnableUNICODE
SDL_FreeSurface
SDL_GL_GetProcAddress
SDL_GL_SetAttribute
SDL_GL_SwapBuffers
SDL_GetAppState
SDL_GetError
SDL_GetKeyName
SDL_GetVideoInfo
SDL_GetVideoSurface
SDL_Has3DNow
SDL_Has3DNowExt
SDL_HasAltiVec
SDL_HasMMX
SDL_HasMMXExt
SDL_HasRDTSC
SDL_HasSSE
SDL_HasSSE2
SDL_Init
SDL_JoystickClose
SDL_JoystickEventState
SDL_JoystickGetAxis
SDL_JoystickGetBall
SDL_JoystickGetButton
SDL_JoystickGetHat
SDL_JoystickName
SDL_JoystickNumAxes
SDL_JoystickNumBalls
SDL_JoystickNumButtons
SDL_JoystickNumHats
SDL_JoystickOpen
SDL_JoystickOpened
SDL_JoystickUpdate
SDL_Linked_Version
SDL_ListModes
SDL_LoadFunction
SDL_LoadObject
SDL_LockAudio
SDL_NumJoysticks
SDL_OpenAudio
SDL_PauseAudio
SDL_PeepEvents
SDL_PollEvent
SDL_PumpEvents
SDL_Quit
SDL_QuitSubSystem
SDL_SetGamma
SDL_SetGammaRamp
SDL_SetVideoMode
SDL_ShowCursor
SDL_UnloadObject
SDL_UnlockAudio
SDL_VideoDriverName
SDL_WM_GrabInput
SDL_WM_IconifyWindow
SDL_WM_SetCaption
SDL_WM_SetIcon
SDL_WM_ToggleFullScreen
SDL_WarpMouse
SDL_WasInit
