vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH REPO DaveGamble/cJSON REF "v${VERSION}" SHA512 7b22bdd05b8e0bf8b24ab79db128dbab9f8c2c167f4b1d3073922b8ff1e0f0e8917322283d6d4091002f014f42692984f4f641761f05965d3b66fb3eca14dc46 HEAD_REF master)
vcpkg_cmake_configure(SOURCE_PATH "${SOURCE_PATH}" OPTIONS -DBUILD_SHARED_LIBS=ON -DBUILD_SHARED_AND_STATIC_LIBS=OFF -DENABLE_CJSON_TEST=ON -DENABLE_CJSON_UTILS=OFF -DENABLE_SANITIZERS=OFF -DENABLE_CUSTOM_COMPILER_FLAGS=OFF -DENABLE_TARGET_EXPORT=ON)
vcpkg_cmake_install()
set(test_build "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel")
set(test_names cJSON_test parse_examples parse_number parse_hex4 parse_string parse_array parse_object parse_value print_string print_number print_array print_object print_value misc_tests parse_with_opts compare_tests cjson_add readme_examples minify_tests)
file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/tools/cjson/upstream-tests")
foreach(test_name IN LISTS test_names)
    if(test_name STREQUAL "cJSON_test")
        set(test_binary "${test_build}/${test_name}")
    else()
        set(test_binary "${test_build}/tests/${test_name}")
    endif()
    file(INSTALL "${test_binary}" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/cjson/upstream-tests" USE_SOURCE_PERMISSIONS)
endforeach()
file(INSTALL "${test_build}/tests/inputs" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/cjson/upstream-tests")
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/cJSON)
vcpkg_fixup_pkgconfig()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include" "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
