[Function]
aec_buffer_decode
aec_buffer_encode
aec_buffer_seek
aec_decode
aec_decode_count_offsets
aec_decode_enable_offsets
aec_decode_end
aec_decode_get_offsets
aec_decode_init
aec_decode_range
aec_encode
aec_encode_count_offsets
aec_encode_enable_offsets
aec_encode_end
aec_encode_get_offsets
aec_encode_init
