[Function]
sws_alloc_context
sws_freeContext
sws_getCoefficients
sws_getColorspaceDetails
sws_get_class
sws_init_context
sws_isSupportedEndiannessConversion
sws_isSupportedInput
sws_isSupportedOutput
sws_scale_frame
sws_setColorspaceDetails
swscale_configuration
swscale_version
