[Function]
XPanoramiXAllocInfo
XPanoramiXGetScreenCount
XPanoramiXGetScreenSize
XPanoramiXGetState
XPanoramiXQueryExtension
XPanoramiXQueryVersion
XineramaIsActive
XineramaQueryExtension
XineramaQueryScreens
XineramaQueryVersion
