[Function]
soxr_clear
soxr_create
soxr_delay
soxr_delete
soxr_engine
soxr_error
soxr_io_spec
soxr_num_clips
soxr_oneshot
soxr_output
soxr_process
soxr_quality_spec
soxr_runtime_spec
soxr_set_input_fn
